### ISSUE TITLE
misalignment of checkbox

### ISSUE THREAD

**Issue by Rounak-28** [atapas/promiviz#11]
**Describe the bug**
The checkbox is not aligned properly with the text

**Screenshots**
![Screenshot 2022-10-05 130920](https://user-images.githubusercontent.com/95576871/194006912-dca6e6bc-d84a-40b5-b32e-1c04b99dd061.jpg)

**Additional context**
I would like to work on this issue.

**Comment by titusjoyson** [comment]
@atapas I like to take this issue

**Comment by atapas** [comment]
> @atapas I like to take this issue

Hey It has been assigned to @Rounak-28 already. Assuming he is on it.
