### ISSUE TITLE
Add custom scrollbar

### ISSUE THREAD

**Issue by Arbtrage** [atapas/promiviz#16]
**Is your feature request related to a problem? Please describe.**
The scroll bar is really basic and would look good if it is modified according to the website's overall theme.

**Describe the solution you'd like**
Would like to add a custom scrollbar to suit the overall vibe of the website.

**Describe alternatives you've considered**
None.

**Additional context**
![newiisue](https://user-images.githubusercontent.com/100552235/194559639-fa28ae8c-b6dc-4ddc-b118-f5602838d482.jpeg)

**Comment by Beela303** [comment]
Could I be assigned to this issue I can use the main colors of the themes to make custom scroll bars with different colors depending on the theme. 

Here are some examples:

![{82ED3CC8-D20F-4297-BB7E-245448228B42} png](https://user-images.githubusercontent.com/87093025/194731456-5b7131c0-9189-408e-9285-f7fbdc2f81b6.jpg)
![{A8A0A9F0-69BC-440A-ACE0-C55E2D3A5164} png](https://user-images.githubusercontent.com/87093025/194731457-3a75838d-9cb8-4843-88dc-9a15362a39a5.jpg)
![{CAC4120B-C377-44B8-96A8-839495690730} png](https://user-images.githubusercontent.com/87093025/194731458-63f5fd01-3e4e-46e9-b2df-0415825a925f.jpg)

**Comment by DhruvLamba** [comment]
Can you please assign me  this issue

**Comment by anupriyajain595** [comment]
Can I resolve this issue??

**Comment by rishabhk1796** [comment]
I have sent a pull request. Please review my code...

**Comment by sayli2003** [comment]
Can I be assigned this issue?

I can give the Scrollbar a gradient.

Heres an example:


![scrollerbar](https://user-images.githubusercontent.com/95756364/196253066-bb6139e3-76a3-4409-bac3-b0b1227261a4.PNG)
