### ISSUE TITLE
Improving Side Menu & Social Icons

### ISSUE THREAD

**Issue by Ayush-Kanduri** [atapas/promiviz#27]
**Is your feature request related to a problem? Please describe.**
No, my work is related to the UI.

**Describe the solution you'd like**
- [ ] Improving the styling & animation of the side menu
- [ ] Adding social icons at the bottom of the page inside the footer, to make it more visible & appealing.

**Additional context**
![Sidebar](https://user-images.githubusercontent.com/76626529/195260737-240f8d0b-d0ea-4481-b1e7-d98e0761aa70.gif)

**Comment by Ayush-Kanduri** [comment]
Hi, could you please assign the issue to me, so that I start working on it ASAP?

**Comment by deepakchowdary19** [comment]
it would be great if i can make my first pr by contributing to this task, can you assign this to me

**Comment by Ayush-Kanduri** [comment]
Hi, I have already created this Issue #27 & made a Pull Request #28 to solve the same.

Kindly review and merge the PR. 
It's for the Hacktoberfest. 
I'd be glad.

**Comment by Ayush-Kanduri** [comment]
> Hi, I have already created this Issue #27 & made a Pull Request #28 to solve the same.
> 
> Kindly review and merge the PR. 
> It's for the Hacktoberfest. 
> I'd be glad.

Hi @atapas can you please review & merge the PR. I'd be glad.

**Comment by Ayush-Kanduri** [comment]
Waited for so long & got no response from the maintainer. Closing the issue.
