### ISSUE TITLE
UI Improvement

### ISSUE THREAD

**Issue by lio2011** [atapas/promiviz#42]
**Is your feature request related to a problem? Please describe.**
The UI is very plain and simple for now

**Describe the solution you'd like**
I would like to improve the look and UX of the website

**Describe alternatives you've considered**
Using custom libraries such as bootstrap can help

**Additional context**

**Comment by lio2011** [comment]
@atapas can you assign this issue to me for hacktoberfest

**Comment by Sa24miksha** [comment]
@atapas I have made a successful PR which have solved all the issues you mentioned please review it
